// 默认微信渠道
export const DEFAULT_WXCHANNEL = 'dypy';

// API
export const CALL_API = 'CALL_API';

// 首页相关
export const LOAD_HOME_ADSLIST_REQUEST = 'LOAD_HOME_ADSLIST_REQUEST';
export const LOAD_HOME_ADSLIST_SUCCESS = 'LOAD_HOME_ADSLIST_SUCCESS';
export const LOAD_HOME_ADSLIST_FAILURE = 'LOAD_HOME_ADSLIST_FAILURE';
export const LOAD_HOME_NEWSLIST_REQUEST = 'LOAD_HOME_NEWSLIST_REQUEST';
export const LOAD_HOME_NEWSLIST_SUCCESS = 'LOAD_HOME_NEWSLIST_SUCCESS';
export const LOAD_HOME_NEWSLIST_FAILURE = 'LOAD_HOME_NEWSLIST_FAILURE';

// 视频列表页
export const LOAD_VIDEOS_ADSLIST_REQUEST = 'LOAD_VIDEOS_ADSLIST_REQUEST';
export const LOAD_VIDEOS_ADSLIST_SUCCESS = 'LOAD_VIDEOS_ADSLIST_SUCCESS';
export const LOAD_VIDEOS_ADSLIST_FAILURE = 'LOAD_VIDEOS_ADSLIST_FAILURE';
export const LOAD_VIDEOS_NEWSLIST_REQUEST = 'LOAD_VIDEOS_NEWSLIST_REQUEST';
export const LOAD_VIDEOS_NEWSLIST_SUCCESS = 'LOAD_VIDEOS_NEWSLIST_SUCCESS';
export const LOAD_VIDEOS_NEWSLIST_FAILURE = 'LOAD_VIDEOS_NEWSLIST_FAILURE';

// 在线电影列表页
export const LOAD_MOVIES_ADSLIST_REQUEST = 'LOAD_MOVIES_ADSLIST_REQUEST';
export const LOAD_MOVIES_ADSLIST_SUCCESS = 'LOAD_MOVIES_ADSLIST_SUCCESS';
export const LOAD_MOVIES_ADSLIST_FAILURE = 'LOAD_MOVIES_ADSLIST_FAILURE';
export const LOAD_MOVIES_NEWSLIST_REQUEST = 'LOAD_MOVIES_NEWSLIST_REQUEST';
export const LOAD_MOVIES_NEWSLIST_SUCCESS = 'LOAD_MOVIES_NEWSLIST_SUCCESS';
export const LOAD_MOVIES_NEWSLIST_FAILURE = 'LOAD_MOVIES_NEWSLIST_FAILURE';
export const REFRESH_MOVIES_NEWSLIST_REQUEST = 'REFRESH_MOVIES_NEWSLIST_REQUEST';
export const REFRESH_MOVIES_NEWSLIST_SUCCESS = 'REFRESH_MOVIES_NEWSLIST_SUCCESS';
export const REFRESH_MOVIES_NEWSLIST_FAILURE = 'REFRESH_MOVIES_NEWSLIST_FAILURE';

// 新闻详情
export const LOAD_NEWS_REQUEST = 'LOAD_NEWS_REQUEST';
export const LOAD_NEWS_SUCCESS = 'LOAD_NEWS_SUCCESS';
export const LOAD_NEWS_FAILURE = 'LOAD_NEWS_FAILURE';

// 公众号相关
export const LOAD_PUBLISHER_NEWSLIST_REQUEST = 'LOAD_PUBLISHER_NEWSLIST_REQUEST';
export const LOAD_PUBLISHER_NEWSLIST_SUCCESS = 'LOAD_PUBLISHER_NEWSLIST_SUCCESS';
export const LOAD_PUBLISHER_NEWSLIST_FAILURE = 'LOAD_PUBLISHER_NEWSLIST_FAILURE';
export const TOGGLE_SUBSCRIBE_PUBLISHER_REQUEST = 'TOGGLE_SUBSCRIBE_PUBLISHER_REQUEST';
export const TOGGLE_SUBSCRIBE_PUBLISHER_SUCCESS = 'TOGGLE_SUBSCRIBE_PUBLISHER_SUCCESS';
export const TOGGLE_SUBSCRIBE_PUBLISHER_FAILURE = 'TOGGLE_SUBSCRIBE_PUBLISHER_FAILURE';

// 支付相关
export const GET_PAY_PARAMS_REQUEST = 'GET_PAY_PARAMS_REQUEST';
export const GET_PAY_PARAMS_SUCCESS = 'GET_PAY_PARAMS_SUCCESS';
export const GET_PAY_PARAMS_FAILURE = 'GET_PAY_PARAMS_FAILURE';
